-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 创建原子性增加发布计数的函数
CREATE OR REPLACE FUNCTION increment_post_count(p_user_id TEXT, p_date DATE)
RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
 UPDATE daily_post_logs
 SET post_count = post_count + 1
 WHERE user_id = p_user_id AND post_date = p_date;
 
 -- 如果没有记录，插入一条
 IF NOT FOUND THEN
 INSERT INTO daily_post_logs (user_id, post_date, post_count)
 VALUES (p_user_id, p_date, 1)
 ON CONFLICT (user_id, post_date) DO UPDATE
 SET post_count = daily_post_logs.post_count + 1;
 END IF;
END;
$$;

