-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

DROP POLICY IF EXISTS "用户可插入自己的资料" ON public.profiles;

CREATE POLICY "允许注册时插入资料" ON public.profiles
FOR INSERT WITH CHECK (true);