-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 用户间留言板 - 对话线表
CREATE TABLE IF NOT EXISTS user_conversations (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_a UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
 user_b UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
 last_message_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE(user_a, user_b)
);

CREATE INDEX idx_conversations_user_a ON user_conversations(user_a);
CREATE INDEX idx_conversations_user_b ON user_conversations(user_b);

ALTER TABLE user_conversations ENABLE ROW LEVEL SECURITY;

-- 对话双方可以查看
CREATE POLICY participants_read_conversation
 ON user_conversations FOR SELECT
 USING (auth.uid() = user_a OR auth.uid() = user_b);

-- 任何人可以新建对话
CREATE POLICY auth_insert_conversation
 ON user_conversations FOR INSERT
 WITH CHECK (auth.uid() = user_a AND user_a != user_b);

