-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 用户主动隐藏状态
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS hide_status TEXT DEFAULT 'none' CHECK (hide_status IN ('none', 'cooling', 'frozen'));

-- 时间节点
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS hide_requested_at TIMESTAMPTZ;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS cooling_ends_at TIMESTAMPTZ;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS frozen_ends_at TIMESTAMPTZ;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS hide_canceled_at TIMESTAMPTZ;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS restored_at TIMESTAMPTZ;

