-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 添加 display_id 字段到 profiles 表
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS display_id INTEGER UNIQUE;

-- 创建序列用于生成数字ID，从 000000000 开始
CREATE SEQUENCE IF NOT EXISTS public.display_id_seq START WITH 0 MINVALUE 0;

-- 创建触发器函数，自动分配 display_id
CREATE OR REPLACE FUNCTION public.assign_display_id()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NEW.display_id IS NULL THEN
    NEW.display_id := nextval('public.display_id_seq');
  END IF;
  RETURN NEW;
END;
$$;

-- 创建触发器
DROP TRIGGER IF EXISTS trigger_assign_display_id ON public.profiles;
CREATE TRIGGER trigger_assign_display_id
  BEFORE INSERT ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.assign_display_id();

-- 为现有用户分配 display_id（如果还没有）
DO $$
DECLARE
  profile_record RECORD;
  current_id INTEGER := 0;
BEGIN
  FOR profile_record IN 
    SELECT id FROM public.profiles WHERE display_id IS NULL ORDER BY created_at ASC
  LOOP
    UPDATE public.profiles SET display_id = current_id WHERE id = profile_record.id;
    current_id := current_id + 1;
  END LOOP;
  
  -- 设置序列的当前值
  IF current_id > 0 THEN
    PERFORM setval('public.display_id_seq', current_id - 1);
  END IF;
END $$;