-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 删除可能导致无限递归的 RLS 策略
DROP POLICY IF EXISTS "管理员可查看所有资料" ON public.profiles;

-- 创建安全定义者函数来检查管理员权限
CREATE OR REPLACE FUNCTION public.is_admin_user(user_uuid UUID)
RETURNS BOOLEAN
LANGUAGE SQL STABLE
SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = user_uuid AND is_admin = true
  );
$$;

-- 重新创建管理员策略，使用安全定义者函数
CREATE POLICY "管理员可查看所有资料" ON public.profiles
FOR ALL USING (
  public.is_admin_user(auth.uid())
);

-- 同样修复 logs 表的管理员策略
DROP POLICY IF EXISTS "管理员可查看所有日志" ON public.logs;

CREATE POLICY "管理员可查看所有日志" ON public.logs
FOR ALL USING (
  public.is_admin_user(auth.uid())
);

-- 修复 background_images 表的管理员策略
DROP POLICY IF EXISTS "管理员可管理所有背景图" ON public.background_images;

CREATE POLICY "管理员可管理所有背景图" ON public.background_images
FOR ALL USING (
  public.is_admin_user(auth.uid())
);