-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS is_frozen BOOLEAN DEFAULT false; ALTER TABLE profiles ADD COLUMN IF NOT EXISTS frozen_at TIMESTAMPTZ; ALTER TABLE profiles ADD COLUMN IF NOT EXISTS frozen_reason TEXT; ALTER TABLE profiles ADD COLUMN IF NOT EXISTS frozen_by UUID REFERENCES auth.users(id);
