-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS guestbook_messages (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
 username TEXT NOT NULL,
 content TEXT NOT NULL CHECK (LENGTH(content) <= 1000),
 is_read BOOLEAN DEFAULT false,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 启用 RLS
ALTER TABLE guestbook_messages ENABLE ROW LEVEL SECURITY;

-- 所有人可以查看留言（公开的）
CREATE POLICY anon_select_guestbook ON guestbook_messages
 FOR SELECT USING (true);

-- 登录用户可以提交自己的留言
CREATE POLICY users_insert_guestbook ON guestbook_messages
 FOR INSERT WITH CHECK (user_id = auth.uid());

-- 用户只能删除自己的留言
CREATE POLICY users_delete_own_guestbook ON guestbook_messages
 FOR DELETE USING (user_id = auth.uid());

