-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建系统背景图表，存储管理员上传的预设背景
CREATE TABLE IF NOT EXISTS public.system_backgrounds (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    url TEXT NOT NULL,
    name TEXT,
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- 允许所有人查看系统背景
ALTER TABLE public.system_backgrounds ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看系统背景图" ON public.system_backgrounds
    FOR SELECT USING (true);

-- 只有管理员可以管理系统背景
CREATE POLICY "只有管理员可管理系统背景图" ON public.system_backgrounds
    FOR ALL USING (
        auth.uid() IN (
            SELECT id FROM public.profiles WHERE is_admin = true
        )
    );