-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS system_config (
 id SERIAL PRIMARY KEY,
 key TEXT NOT NULL UNIQUE,
 value TEXT NOT NULL,
 created_at TIMESTAMPTZ DEFAULT NOW(),
 updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 初始化配置
INSERT INTO system_config (key, value) VALUES
 ('global_message_board_enabled', 'true'),
 ('message_rate_limit', '10'),
 ('captcha_required', 'true')
ON CONFLICT (key) DO NOTHING;

