-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS reports (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), reporter_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, reported_message_id UUID NOT NULL, message_table TEXT NOT NULL CHECK (message_table IN ('guestbook_messages', 'user_messages', 'logs', 'profiles')), message_content TEXT NOT NULL, reported_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, reason TEXT NOT NULL CHECK (LENGTH(reason) <= 200), status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'dismissed')), admin_notes TEXT, reviewed_by UUID REFERENCES auth.users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), reviewed_at TIMESTAMPTZ);
