-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 为 guestbook 表添加审核相关字段
ALTER TABLE guestbook ADD COLUMN status TEXT DEFAULT 'pending';
ALTER TABLE guestbook ADD COLUMN visible_after TIMESTAMPTZ;

-- 更新现有数据：已存在的留言设置为已审核状态
UPDATE guestbook SET status = 'approved', visible_after = created_at WHERE status IS NULL OR status = 'pending';

