-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


ALTER TABLE profiles ADD COLUMN IF NOT EXISTS slogan_approved BOOLEAN DEFAULT false;

-- 更新现有数据：有slogan的设为false，没有的保持null
UPDATE profiles SET slogan_approved = false WHERE slogan IS NOT NULL AND slogan != '' AND slogan_approved IS NULL;

