-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建 profiles 表
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT NOT NULL,
  user_id TEXT UNIQUE NOT NULL,
  tag TEXT NOT NULL,
  slogan TEXT,
  location TEXT NOT NULL,
  is_public BOOLEAN DEFAULT true,
  is_hidden BOOLEAN DEFAULT false,
  is_admin BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 创建 logs 表
CREATE TABLE IF NOT EXISTS public.logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL REFERENCES public.profiles(user_id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 创建 edit_tokens 表
CREATE TABLE IF NOT EXISTS public.edit_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL,
  token TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 创建 ip_blacklist 表
CREATE TABLE IF NOT EXISTS public.ip_blacklist (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cidr TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 创建 background_images 表
CREATE TABLE IF NOT EXISTS public.background_images (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL REFERENCES public.profiles(user_id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  is_active BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_profiles_user_id ON public.profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_profiles_username ON public.profiles(username);
CREATE INDEX IF NOT EXISTS idx_logs_user_id ON public.logs(user_id);
CREATE INDEX IF NOT EXISTS idx_logs_created_at ON public.logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_edit_tokens_user_id ON public.edit_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_edit_tokens_token ON public.edit_tokens(token);
CREATE INDEX IF NOT EXISTS idx_ip_blacklist_cidr ON public.ip_blacklist(cidr);
CREATE INDEX IF NOT EXISTS idx_background_images_user_id ON public.background_images(user_id);
CREATE INDEX IF NOT EXISTS idx_background_images_status ON public.background_images(status);

-- 创建 storage bucket
INSERT INTO storage.buckets (id, name, public)
VALUES ('backgrounds', 'backgrounds', true)
ON CONFLICT (id) DO NOTHING;

-- 插入默认 IP 黑名单
INSERT INTO public.ip_blacklist (cidr, description) VALUES
('103.21.244.0/22', 'Cloudflare IP Range'),
('103.22.200.0/22', 'Cloudflare IP Range'),
('103.31.4.0/22', 'Cloudflare IP Range'),
('104.16.0.0/13', 'Cloudflare IP Range'),
('104.24.0.0/14', 'Cloudflare IP Range'),
('108.162.192.0/18', 'Cloudflare IP Range'),
('131.0.72.0/22', 'Cloudflare IP Range'),
('141.101.64.0/18', 'Cloudflare IP Range'),
('162.158.0.0/15', 'Cloudflare IP Range'),
('172.64.0.0/13', 'Cloudflare IP Range'),
('173.245.48.0/20', 'Cloudflare IP Range'),
('188.114.96.0/20', 'Cloudflare IP Range'),
('190.93.240.0/20', 'Cloudflare IP Range'),
('197.234.240.0/22', 'Cloudflare IP Range'),
('198.41.128.0/17', 'Cloudflare IP Range')
ON CONFLICT DO NOTHING;

-- 启用 RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.edit_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ip_blacklist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.background_images ENABLE ROW LEVEL SECURITY;

-- profiles 表 RLS 策略
CREATE POLICY "所有人可查看公开资料" ON public.profiles
FOR SELECT USING (is_public = true AND is_hidden = false);

CREATE POLICY "用户可查看自己的资料" ON public.profiles
FOR SELECT USING (auth.uid() = id);

CREATE POLICY "用户可更新自己的资料" ON public.profiles
FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "管理员可查看所有资料" ON public.profiles
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND is_admin = true
  )
);

-- logs 表 RLS 策略
CREATE POLICY "所有人可查看公开用户日志" ON public.logs
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE user_id = logs.user_id AND is_public = true AND is_hidden = false
  )
);

CREATE POLICY "用户可查看自己的日志" ON public.logs
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND user_id = logs.user_id
  )
);

CREATE POLICY "用户可创建自己的日志" ON public.logs
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND user_id = logs.user_id
  )
);

-- edit_tokens 表 RLS 策略
CREATE POLICY "用户可管理自己的编辑令牌" ON public.edit_tokens
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND user_id = edit_tokens.user_id
  )
);

-- ip_blacklist 表 RLS 策略 (仅管理员可管理)
CREATE POLICY "管理员可管理IP黑名单" ON public.ip_blacklist
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND is_admin = true
  )
);

CREATE POLICY "所有人可查看IP黑名单" ON public.ip_blacklist
FOR SELECT USING (true);

-- background_images 表 RLS 策略
CREATE POLICY "所有人可查看已审核背景图" ON public.background_images
FOR SELECT USING (status = 'approved');

CREATE POLICY "用户可管理自己的背景图" ON public.background_images
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND user_id = background_images.user_id
  )
);

-- Storage RLS 策略
CREATE POLICY "允许查看背景图" ON storage.objects
FOR SELECT USING (bucket_id = 'backgrounds');

CREATE POLICY "允许上传背景图" ON storage.objects
FOR INSERT WITH CHECK (
  bucket_id = 'backgrounds' AND
  auth.role() = 'authenticated'
);

CREATE POLICY "允许删除自己的背景图" ON storage.objects
FOR DELETE USING (
  bucket_id = 'backgrounds' AND
  auth.uid()::text = (storage.foldername(name))[1]
);