-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE INDEX idx_reports_status ON reports(status, created_at); CREATE INDEX idx_reports_reported_user ON reports(reported_user_id);
