-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 初始化发布限额配置
INSERT INTO system_config (key, value) VALUES
 ('daily_post_limit_user', '10'),
 ('daily_post_limit_verified', '10'),
 ('daily_post_limit_premium', '30')
ON CONFLICT (key) DO NOTHING;

