-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 添加用户等级字段到 profiles 表
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'user' CHECK (role IN ('user', 'verified', 'premium'));

-- 添加今日发布计数字段
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS daily_posts_count INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS last_post_date DATE;

-- 创建日志发布记录表（用于精确统计每日发布）
CREATE TABLE IF NOT EXISTS daily_post_logs (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id TEXT NOT NULL REFERENCES profiles(user_id) ON DELETE CASCADE,
 post_date DATE NOT NULL DEFAULT CURRENT_DATE,
 post_count INTEGER NOT NULL DEFAULT 1,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE(user_id, post_date)
);

-- 启用 RLS
ALTER TABLE daily_post_logs ENABLE ROW LEVEL SECURITY;

-- 用户只能查看自己的发布记录
CREATE POLICY users_select_own_post_logs ON daily_post_logs
 FOR SELECT USING (user_id = (SELECT user_id FROM profiles WHERE id = auth.uid()));

-- 匿名插入策略（用于发布时记录）
CREATE POLICY anon_insert_post_logs ON daily_post_logs
 FOR INSERT WITH CHECK (true);

-- 更新策略
CREATE POLICY users_update_own_post_logs ON daily_post_logs
 FOR UPDATE USING (user_id = (SELECT user_id FROM profiles WHERE id = auth.uid()));

