-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 用户间留言板 - 消息内容表
CREATE TABLE IF NOT EXISTS user_messages (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 conversation_id UUID NOT NULL REFERENCES user_conversations(id) ON DELETE CASCADE,
 sender_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
 sender_username TEXT NOT NULL,
 content TEXT NOT NULL CHECK (LENGTH(content) <= 500),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 is_deleted BOOLEAN DEFAULT false
);

CREATE INDEX idx_messages_conversation ON user_messages(conversation_id, created_at);

ALTER TABLE user_messages ENABLE ROW LEVEL SECURITY;

-- 对话参与者可以查看消息
CREATE POLICY participants_read_messages
 ON user_messages FOR SELECT
 USING (
 EXISTS (
 SELECT 1 FROM user_conversations c
 WHERE c.id = user_messages.conversation_id
 AND (c.user_a = auth.uid() OR c.user_b = auth.uid())
 )
 OR auth.uid() IS NOT NULL
 );

-- 登录用户可以发送消息
CREATE POLICY auth_insert_message
 ON user_messages FOR INSERT
 WITH CHECK (auth.uid() = sender_id);

-- 发送者可在 10 分钟内删除
CREATE POLICY sender_delete_own_message
 ON user_messages FOR DELETE
 USING (auth.uid() = sender_id AND created_at > NOW() - INTERVAL '10 minutes');

-- 管理员可以删除任何消息
CREATE POLICY admin_delete_message
 ON user_messages FOR DELETE
 USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin = true));

