-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 为 logs 表添加公开相关字段
ALTER TABLE logs ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT false;
ALTER TABLE logs ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ;

-- 更新现有数据：已存在的日志视为已公开
UPDATE logs SET is_public = true, published_at = created_at WHERE is_public IS NULL;

-- 添加索引优化查询
CREATE INDEX IF NOT EXISTS idx_logs_is_public ON logs(is_public);
CREATE INDEX IF NOT EXISTS idx_logs_published_at ON logs(published_at);
CREATE INDEX IF NOT EXISTS idx_logs_user_id_created ON logs(user_id, created_at DESC);

