-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS guestbook (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id TEXT NOT NULL,
 content TEXT NOT NULL,
 is_public BOOLEAN DEFAULT true,
 created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 添加 RLS 策略
ALTER TABLE guestbook ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_guestbook ON guestbook
 FOR SELECT
 USING (is_public = true);

CREATE POLICY anon_insert_guestbook ON guestbook
 FOR INSERT
 WITH CHECK (true);

CREATE POLICY users_delete_own_guestbook ON guestbook
 FOR DELETE
 USING (user_id = current_user);

