-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 添加站点地图模式配置（默认静态模式）
INSERT INTO system_config (key, value) VALUES ('sitemap_mode', 'static')
ON CONFLICT (key) DO NOTHING;

