-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 1. 为 conversations 表添加公开相关字段
ALTER TABLE conversations ADD COLUMN is_public BOOLEAN DEFAULT false;
ALTER TABLE conversations ADD COLUMN public_title TEXT;
ALTER TABLE conversations ADD COLUMN public_at TIMESTAMPTZ;

